### PR TITLE
Rearranged

### PR DESCRIPTION
**Pull request by ngoquang2708**

### CODE REVIEW

**Comment by ngoquang2708** [comment]
@koquantam I added support to your board, please check it out.
@corphish I updated my hardware tree, please check it out and add support to your board.

**Comment by koquantam** [comment]
Merged

**Comment by koquantam** [comment]
However, there're some parts of these HAL needs board-specific source, like HWC or gralloc, OMX. We need specified board redirection in Android.mk using "ifeq", like with hwc/sc8830 or hwc/scx15, we use Android.mk in hwc source folder to locate source for each boards, so we don't have to play around with compile error

**Comment by ngoquang2708** [comment]
I've done it!

**Comment by koquantam** [comment]
Sorry, just discovered it :D

**Comment by corphish** [comment]
Alright. Doing it when I get chance.
Implementation is perfect like its found in hardware/qcom/*/<various board platforms>
CM maintains separate repos for all LOL.
We wont be doing that anyway.

**Pull request merged**
